name: CI/CD Pipeline

on:
  push:
    branches:
      - test

jobs:
  deploy:
    name: Deploy to Server
    runs-on: ubuntu-latest

    steps:
      - name: Clone or Update Repository and Build Docker
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            # Создаем директорию, если её нет
            if [ ! -d "~/myapp-directory" ]; then
              echo "Cloning the repository for the first time..."
              git clone https://github.com/${{ github.repository }} ~/myapp-directory
            else
              echo "Repository exists. Pulling the latest changes..."
              cd ~/myapp-directory
              git fetch --all
              git checkout test
              git pull origin test
            fi

            # Переход в нужную директорию
            cd ~/myapp-directory/Sulpak.TestAssigment

            # Остановка старого контейнера
            echo "Stopping existing container..."
            sudo docker stop myapp-container || true
            sudo docker rm myapp-container || true

            # Сборка и запуск нового контейнера
            echo "Building Docker image..."
            sudo docker build -t myapp .

            echo "Running the new container..."
            sudo docker run -d --name myapp-container -p 8080:8080 -p 8081:8081 myapp

            echo "Deployment completed successfully!"
