name: CI/CD Pipeline

on:
  push:
    branches:
      - test

jobs:
  deploy:
    name: Deploy to Server
    runs-on: ubuntu-latest

    steps:
      # Шаг 1: Клонирование репозитория
      - name: Checkout Code
        uses: actions/checkout@v4

      # Шаг 2: Копирование файлов на сервер
      - name: Copy Files to Server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "./"   # Передаём все файлы из репозитория
          target: "~/myapp-directory" # Куда копировать файлы на сервер
          strip-components: 0

      # Шаг 3: Проверка содержимого директории на сервере
      - name: Check Files on Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            echo "### Проверка директории ~/myapp-directory ###"
            ls -R ~/myapp-directory

      # Шаг 4: Подключение и сборка образа
      - name: Build and Deploy on Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            # Переход в директорию
            cd ~/myapp-directory

            # Проверка наличия Dockerfile
            if [ ! -f ./Sulpak.TestAssigment.PublicApi/Dockerfile ]; then
              echo "Error: Dockerfile not found in Sulpak.TestAssigment.PublicApi!"
              exit 1
            fi

            # Остановка и удаление старого контейнера
            sudo docker stop myapp-container || true
            sudo docker rm myapp-container || true

            # Сборка Docker-образа
            sudo docker build -t myapp ./Sulpak.TestAssigment.PublicApi/

            # Запуск нового контейнера
            sudo docker run -d --name myapp-container -p 8080:8080 -p 8081:8081 myapp
            echo "Deployment completed successfully!"
